server:
  port: 8800
spring:
  application:
    name: cloud-provider #\u4e3a\u4f60\u7684\u5e94\u7528\u8d77\u4e2a\u540d\u5b57\uff0c\u8be5\u540d\u5b57\u5c06\u6ce8\u518c\u5230eureka\u6ce8\u518c\u4e2d\u5fc3
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #\u53bb\u54ea\u91cc\u6ce8\u518c\uff0ceureka\u670d\u52a1\u5730\u5740